#!/bin/bash
#SBATCH -A WHEELER-SL2-CPU
#SBATCH -p skylake
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -t 00:01:00
#SBATCH -J matlab-example
#SBATCH -o matlab_example.out
#SBATCH -e matlab_example.err

module purge
module load rhel7/default-peta4 matlab

matlab -nodisplay -r "feature('numcores'); quit"
